### ISSUE TITLE
IN: Role Assignment

### ISSUE THREAD

**Issue by sina-jamshidi** [hatchways/team-fruit-loops#13]
- Show current players and their positions. Display current host and current players turn.
- When a player selects a role, the game engine will be modified, and then it should broadcast to all players currently in the waiting room what changed
- Relay the game engine via websockets
- {match: {gameEngine}, id: “387489327” }

**Comment by Travmatth** [comment]
Front End API:
`on("role_taken", red|blue field agent|spy master, user)`
`emit("assume_role", red|blue field agent|spy master, user)`


will also need `matchID` for `copy` button, user for html & api calls, start match either an http endpoint or ws event

**Comment by Travmatth** [comment]
closed with #42
