### ISSUE TITLE
IN: New game

### ISSUE THREAD

**Issue by sina-jamshidi** [hatchways/team-fruit-loops#16]
When you create a match, for now it'll store globally in memory. In the future, we can talk about how to properly optimize for this (we can add a Redis server)

Start a new game engine 
We are storing in memory
The host is the person who created the new game
Anyone who joins that ID, will be given the game engine

**Comment by Travmatth** [comment]
Front End API:
`emit("join_by_id", gameID, user)`
`emit("join_by_random", user)`
`emit("join_by_new_public", user)`
`emit("join_by_new_private", user)`

**Comment by Travmatth** [comment]
closed with #39
