### ISSUE TITLE
FE: Assigning Roles

### ISSUE THREAD

**Issue by sina-jamshidi** [hatchways/team-fruit-loops#5]
When you click on "New Game" (public or private), you need to be put in a "waiting room" and assign roles. 

- There are no UI for this so please take creative decision over here. 
- When assigning roles, it needs to follow the game rules:

4 roles
- Red Spy Master
- Red Field Agent
- Blue Spy Master
- Blue Field Agent

Spy Masters: only max 1 person in each coloured role
Field Agent: at least 1 person in each coloured red
Only when all 4 roles have been filled, you’re allowed to start a match

**Comment by mpmpx** [comment]
Closed by merging PR #42
